default:
    pattern:   /
    defaults:  { _controller: pfeServerBundle:Job:list }

Jobs:
    resource: "@pfeServerBundle/Controller/JobController.php"
    type: annotation
    
Workers:
    resource: "@pfeServerBundle/Controller/WorkerController.php"
    type: annotation
    
Users:
    resource: "@pfeServerBundle/Controller/UserController.php"
    type: annotation
    
Groups:
    resource: "@pfeServerBundle/Controller/GroupController.php"
    type: annotation
    
login:
    pattern:   /login
    defaults:  { _controller: pfeServerBundle:Security:login }
    
login_check:
    pattern:   /login_check